apiVersion: v1
kind: Service
metadata:
  name: ort-server-ui
  namespace: {{ .Release.Namespace }}
  labels:
    app: ort-server-ui
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.ui.service.port }}
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: ort-server-ui
