/*
 * Copyright (C) 2025 The ORT Server Authors (See <https://github.com/eclipse-apoapsis/ort-server/blob/main/NOTICE>)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * SPDX-License-Identifier: Apache-2.0
 * License-Filename: LICENSE
 */

package org.eclipse.apoapsis.ortserver.workers.common.env

import org.eclipse.apoapsis.ortserver.workers.common.env.definition.GradleDefinition

/**
 * A specialized generator class to generate the content of the _init.gradle.kts_ file.
 *
 * See https://docs.gradle.org/current/userguide/init_scripts.html.
 */
class GradleInitGenerator : EnvironmentConfigGenerator<GradleDefinition> {
    companion object {
        /** The name of the file that is generated by this generator. */
        private const val TARGET_NAME = ".gradle/init.gradle.kts"
    }
    override val environmentDefinitionType: Class<GradleDefinition> = GradleDefinition::class.java

    override suspend fun generate(builder: ConfigFileBuilder, definitions: Collection<GradleDefinition>) {
        builder.buildInUserHome(TARGET_NAME) {}
    }
}
