# Copyright (C) 2022 The ORT Server Authors (See <https://github.com/eclipse-apoapsis/ort-server/blob/main/NOTICE>)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0
# License-Filename: LICENSE

# Configuration of detekt rule sets, see https://arturbosch.github.io/detekt/comments.html.
# This file only lists the differences to the default configuration at
# https://github.com/arturbosch/detekt/blob/master/detekt-cli/src/main/resources/default-detekt-config.yml.

comments:
  AbsentOrWrongFileLicense:
    active: true
    excludes: ['**/build/generated/**']
    licenseTemplateFile: '.detekt.license.template'
    licenseTemplateIsRegex: true

complexity:
  CyclomaticComplexMethod:
    threshold: 33
  LongMethod:
    threshold: 158
  LongParameterList:
    constructorThreshold: 11
    functionThreshold: 11
  NestedBlockDepth:
    threshold: 10
  TooManyFunctions:
    thresholdInClasses: 19
    thresholdInObjects: 14

coroutines:
  InjectDispatcher:
    active: false

# Formatting rules are implemented via the ktlint plugin. As ktlint does not allow exceptions, we need to disable
# respective rules completely.
formatting:
  AnnotationOnSeparateLine:
    active: false
  ChainWrapping:
    active: false
  CommentWrapping:
    active: false
  FinalNewline:
    active: false
  ImportOrdering:
    active: false
  Indentation:
    active: false
  MaximumLineLength:
    active: false
  NoUnusedImports:
    active: false
  NoWildcardImports:
    active: false
  ParameterListWrapping:
    active: false
  SpacingBetweenDeclarationsWithAnnotations:
    active: false

naming:
  InvalidPackageDeclaration:
    active: false

performance:
  SpreadOperator:
    active: false

style:
  ForbiddenComment:
    active: false
  ForbiddenMethodCall:
    active: true
    # Use org.eclipse.apoapsis.ortserver.utils.logging.runBlocking to make sure the MDC context is preserved.
    # An exception to that is code where the MDC context is not relevant, e.g., in tests.
    methods: ['kotlinx.coroutines.runBlocking']
    excludes: ['**/cli/**'] # The CLI does not have accees to the utils package, therefore, exclude it for this rule.
  LoopWithTooManyJumpStatements:
    active: false
  MagicNumber:
    active: false
  ReturnCount:
    active: false
  SpacingBetweenPackageAndImports:
    active: true
  ThrowsCount:
    max: 5
  UnusedImports:
    active: true
  WildcardImport:
    excludes: ''
    excludeImports:
      - org.eclipse.apoapsis.ortserver.core.plugins.*

ORT:
  OrtImportOrder:
    active: true
    autoCorrect: true
  OrtPackageNaming:
    # TODO: Implement package naming check for ort-server.
    active: false
