excludes:
  paths:
  - pattern: "**/src/{:funTest|test}/**"
    reason: "TEST_OF"
    comment: >-
      Licenses contained in this directory are used for testing and do not apply to the ORT server.
  scopes:
  - pattern: ".*[tT]est.*"
    reason: "TEST_DEPENDENCY_OF"
    comment: >-
      Packages for testing only. Not part of released artifacts.
  - pattern: "detekt.*"
    reason: "DEV_DEPENDENCY_OF"
    comment: >-
      Packages for static code analysis.

curations:
  packages:
  - id: "Maven:org.ossreviewtoolkit.utils:spdx-utils:"
    curations:
      concluded_license: 'Apache-2.0'
      comment: |
        The SPDX utils contain a list of every known license. Conclude the license as this is an ORT internal
        dependency and we can be sure that the license is in fact Apache-2.0.

resolutions:
  issues:
  - message: "ERROR: Timeout after .+ seconds while scanning file 'rules/matrixseqexpl.json'."
    reason: SCANNER_ISSUE
    comment: "This file does not contain any license declarations."
  vulnerabilities:
  - id: "CVE-2022-40150"
    reason: "INEFFECTIVE_VULNERABILITY"
    comment: |
      This vulnerability is reported for the jettison package which is a transitive dependency of the SW360 client used
      by the ORT scanner. The component is vulnerable to Denial of Service attacks causing out of memory errors for
      specially crafted parser inputs. Since it is used here only to parse responses of valid SW360 servers, this is not
      an issue.
  - id: "CVE-2022-45685"
    reason: "INEFFECTIVE_VULNERABILITY"
    comment: |
      This vulnerability is reported for the jettison package which is a transitive dependency of the SW360 client used
      by the ORT scanner. The component is vulnerable to Denial of Service attacks due to uncontrolled recursion for
      specially crafted parser input. Since it is used only to parse responses of valid SW360 servers, this is not an
      issue.
