# SPDX-FileCopyrightText: 2024 The ORT Server Authors (See <https://github.com/eclipse-apoapsis/ort-server/blob/main/NOTICE>)
# SPDX-License-Identifier: CC0-1.0

version = 1
SPDX-PackageName = "OSS Review Toolkit Server"
SPDX-PackageDownloadLocation = "https://github.com/oss-review-toolkit/ort-server"

[[annotations]]
path = "**.dockerignore"
SPDX-FileCopyrightText = "2024 The ORT Server Authors (See <https://github.com/eclipse-apoapsis/ort-server/blob/main/NOTICE>)"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = ".git**"
SPDX-FileCopyrightText = "2022 The ORT Server Authors (See <https://github.com/eclipse-apoapsis/ort-server/blob/main/NOTICE>)"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "**.gitignore"
SPDX-FileCopyrightText = "2024 The ORT Server Authors (See <https://github.com/eclipse-apoapsis/ort-server/blob/main/NOTICE>)"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = ".detekt.license.template"
SPDX-FileCopyrightText = "2022 The ORT Server Authors (See <https://github.com/eclipse-apoapsis/ort-server/blob/main/NOTICE>)"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = ".env.development"
SPDX-FileCopyrightText = "2022 The ORT Server Authors (See <https://github.com/eclipse-apoapsis/ort-server/blob/main/NOTICE>)"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = ".idea/icon*.png"
SPDX-FileCopyrightText = "2024 The ORT Server Authors (See <https://github.com/eclipse-apoapsis/ort-server/blob/main/NOTICE>)"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = ".idea/copyright/*"
SPDX-FileCopyrightText = "2025 The ORT Server Authors (See <https://github.com/eclipse-apoapsis/ort-server/blob/main/NOTICE>)"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = ".mailmap"
SPDX-FileCopyrightText = "2024 The ORT Server Authors (See <https://github.com/eclipse-apoapsis/ort-server/blob/main/NOTICE>)"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = ".run/*.xml"
SPDX-FileCopyrightText = "2022 The ORT Server Authors (See <https://github.com/eclipse-apoapsis/ort-server/blob/main/NOTICE>)"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "gradle/gradle-daemon-jvm.properties"
SPDX-FileCopyrightText = "2024 The ORT Server Authors (See <https://github.com/eclipse-apoapsis/ort-server/blob/main/NOTICE>)"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "CONTRIBUTING.md"
SPDX-FileCopyrightText = "2024 The ORT Server Authors (See <https://github.com/eclipse-apoapsis/ort-server/blob/main/NOTICE>)"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "integrations/completions/**"
SPDX-FileCopyrightText = "2025 The ORT Server Authors (See <https://github.com/eclipse-apoapsis/ort-server/blob/main/NOTICE>)"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "integrations/schemas/**"
SPDX-FileCopyrightText = "2025 The ORT Project Authors (See <https://github.com/eclipse-apoapsis/ort-server/blob/main/NOTICE>)"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "NOTICE"
SPDX-FileCopyrightText = "2022 The ORT Server Authors (See <https://github.com/eclipse-apoapsis/ort-server/blob/main/NOTICE>)"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "README.md"
SPDX-FileCopyrightText = "2022 The ORT Server Authors (See <https://github.com/eclipse-apoapsis/ort-server/blob/main/NOTICE>)"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "renovate.json"
SPDX-FileCopyrightText = "2024 The ORT Server Authors (See <https://github.com/eclipse-apoapsis/ort-server/blob/main/NOTICE>)"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "**/package.json"
SPDX-FileCopyrightText = "2024 The ORT Server Authors (See <https://github.com/eclipse-apoapsis/ort-server/blob/main/NOTICE>)"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "**/pnpm-lock.yaml"
SPDX-FileCopyrightText = "2024 The ORT Server Authors (See <https://github.com/eclipse-apoapsis/ort-server/blob/main/NOTICE>)"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "**/README.md"
SPDX-FileCopyrightText = "2022 The ORT Server Authors (See <https://github.com/eclipse-apoapsis/ort-server/blob/main/NOTICE>)"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "**/tsconfig.*json"
SPDX-FileCopyrightText = "2024 The ORT Server Authors (See <https://github.com/eclipse-apoapsis/ort-server/blob/main/NOTICE>)"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "assets/**"
SPDX-FileCopyrightText = "2024 The ORT Server Authors (See <https://github.com/eclipse-apoapsis/ort-server/blob/main/NOTICE>)"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "**/config/**/*.txt"
SPDX-FileCopyrightText = "2022 The ORT Server Authors (See <https://github.com/eclipse-apoapsis/ort-server/blob/main/NOTICE>)"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "docs/**"
SPDX-FileCopyrightText = "2022 The ORT Server Authors (See <https://github.com/eclipse-apoapsis/ort-server/blob/main/NOTICE>)"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "scripts/**"
SPDX-FileCopyrightText = "2022 The ORT Server Authors (See <https://github.com/eclipse-apoapsis/ort-server/blob/main/NOTICE>)"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "**/resources/**/*.rules.kts"
SPDX-FileCopyrightText = "2022 The ORT Server Authors (See <https://github.com/eclipse-apoapsis/ort-server/blob/main/NOTICE>)"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "**/resources/**/*.sql"
SPDX-FileCopyrightText = "2022 The ORT Server Authors (See <https://github.com/eclipse-apoapsis/ort-server/blob/main/NOTICE>)"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "**/resources/**/*.template"
SPDX-FileCopyrightText = "2022 The ORT Server Authors (See <https://github.com/eclipse-apoapsis/ort-server/blob/main/NOTICE>)"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "**/resources/**/*.yml"
SPDX-FileCopyrightText = "2022 The ORT Server Authors (See <https://github.com/eclipse-apoapsis/ort-server/blob/main/NOTICE>)"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "**/resources/*config*"
SPDX-FileCopyrightText = "2022 The ORT Server Authors (See <https://github.com/eclipse-apoapsis/ort-server/blob/main/NOTICE>)"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "**/resources/META-INF/services/*"
SPDX-FileCopyrightText = "2022 The ORT Server Authors (See <https://github.com/eclipse-apoapsis/ort-server/blob/main/NOTICE>)"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "ui/.prettier*"
SPDX-FileCopyrightText = "2024 The ORT Server Authors (See <https://github.com/eclipse-apoapsis/ort-server/blob/main/NOTICE>)"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "ui/components.json"
SPDX-FileCopyrightText = "2024 The ORT Server Authors (See <https://github.com/eclipse-apoapsis/ort-server/blob/main/NOTICE>)"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "ui/public/**"
SPDX-FileCopyrightText = "2024 The ORT Server Authors (See <https://github.com/eclipse-apoapsis/ort-server/blob/main/NOTICE>)"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "ui/src/api/**"
SPDX-FileCopyrightText = "2024 The ORT Server Authors (See <https://github.com/eclipse-apoapsis/ort-server/blob/main/NOTICE>)"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "ui/src/routeTree.gen.ts"
SPDX-FileCopyrightText = "2024 The ORT Server Authors (See <https://github.com/eclipse-apoapsis/ort-server/blob/main/NOTICE>)"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "website/**"
SPDX-FileCopyrightText = "2024 The ORT Server Authors (See <https://github.com/eclipse-apoapsis/ort-server/blob/main/NOTICE>)"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "website/static/img/ort-logo.svg"
SPDX-FileCopyrightText = "2017 The ORT Project Authors (see <https://github.com/oss-review-toolkit/ort/blob/main/NOTICE>)"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "ui/src/assets/cyclonedx-logo*.svg"
SPDX-FileCopyrightText = "2018 OWASP Foundation, Inc (see <https://cyclonedx.org/about/branding/>)"
SPDX-License-Identifier = "CC-BY-ND-4.0"

[[annotations]]
path = "ui/src/assets/home-icon.svg"
SPDX-FileCopyrightText = "2024 The ORT Server Authors (See <https://github.com/eclipse-apoapsis/ort-server/blob/main/NOTICE>)"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "ui/src/assets/spdx-logo-color.svg"
SPDX-FileCopyrightText = "2011 The Linux Foundation"
SPDX-License-Identifier = "CC-BY-3.0"

[[annotations]]
path = "gradlew*"
SPDX-FileCopyrightText = "2007-2021 The original author or authors <info@gradle.com>"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "gradle/wrapper/**"
SPDX-FileCopyrightText = "2007-2021 The original author or authors <info@gradle.com>"
SPDX-License-Identifier = "Apache-2.0"
