# Database credentials
database.username=postgres
database.password=postgres

# Keycloak credentials
keycloak.apiSecret=4WWmIYAPN4rOv7JfMmKzYGaxrI2NO5pr

# Messaging credentials
rabbitMqUser=admin
rabbitMqPassword=admin
