apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ort-server-orchestrator
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - update
      - watch
