= Instructions for Helm charts

== Preparations

==== Configure Minikube

Start minikube with one node due the limitation that `minikube mount` can only mount to one node.

 minikube start --nodes 1

Create the namespace for all the future deployments and enable it with https://github.com/ahmetb/kubectx/blob/master/kubens[KubeNS]:

----
kubectl create namespace ort-server
kubens ort-server
----

==== Configure Helm

Add the Bitnami repository to your Helm command:

 helm repo add bitnami https://charts.bitnami.com/bitnami

==== Delete previous database (if any)

Please also delete your database content. Bitnami Helm charts create a specific configuration, which is skipped by Postgres' Docker entrypoint if a database already exists.

Therefore, with:

 minikube ssh

you can make sure that `/data/postgres-pv` is empty.

==== Initialize Docker engine

.We need to configure the Docker CLI to connect it to the Docker Engine inside Minikube. This allows:
* Building images to Minikube Docker registry
* Listing images from this registry (with `docker images`)
* Listing Docker containers running in Minikube's Docker Engine (with `docker ps`)

Run once per shell to expose the Docker Engine inside Minikube:

 eval $(minikube docker-env)

==== Build the required Docker images

Build the required Docker images in the cluster.
See https://minikube.sigs.k8s.io/docs/handbook/pushing/ for alternatives.

First the base image for the Analyzer Worker:

 workers/analyzer/docker$ DOCKER_BUILDKIT=1 docker build . -f Analyzer.Dockerfile -t ort-server-analyzer-worker-base-image:latest

Then the different images of ORT Server:

 ./gradlew :core:jibDockerBuild
 ./gradlew :orchestrator:jibDockerBuild
 ./gradlew :workers:analyzer:jibDockerBuild

==== Mount initialization directory

Finally, mount the directory containing Keycloak initialization script:

 minikube mount docker/keycloak:/data/init-keycloak &

== Usage

When a dependency changes in the chart, run:

 scripts/helm/ort-server$ helm dependency update

Validate the syntax of the chart:

 scripts/helm/$ helm lint ort-server

View the Kubernetes configuration generated by the template engine:

 scripts/helm/$ helm template ort-server ort-server

Install the chart in Kubernetes:

 scripts/helm/$ helm install ort-server ./ort-server

To Uninstall the chart run:

 scripts/helm/$ helm uninstall ort-server

##Make sure all the pods are terminated and persistent volume claims have been removed, since Keycloak takes some time to shut down. ##

For that, you can use:

  watch kubectl get pods

There is also a command _upgrade_, but it does not seem to redeploy correctly the resources. Additionally, https://docs.bitnami.com/kubernetes/infrastructure/postgresql/administration/upgrade/[special care] should be taken because the secrets are autogenerated.

Hence, for now I would recommend to always do an ``uninstall``.

==== (Optional) Create an archive for the chart

Create a _.tgz_ of a chart for redistribution:

 helm package ort-server

==== Access the remote services on the host

Keycloak needs to have the exact same domain and port as in the cluster to avoid running into a JWT validation error because of issuer change.
Same for Postgres for consistency.

The solution here is to start the following command (it should not be stopped):

 minikube tunnel --bind-address=127.0.0.1

Then add an alias to localhost in the /etc/hosts file (or your platform equivalent) for each service being exposed:

 127.0.0.1       localhost keycloak postgres artemis core

Afterwards, you can configure a local ORT Service with the following JDBC URL:

 jdbc:postgresql://postgres:5432

And you can send requests to the ORT Server using the following Keycloak URLs:

----
Authorization URL: http://keycloak:8081/realms/master/protocol/openid-connect/auth
Access Token URL: http://keycloak:8081/realms/master/protocol/openid-connect/token
----

And you can send requests to the _core_ module of the ORT Server. Its SwaggerUI is reachable under the following URL:

  http://core:8080/swagger-ui/index.html
