apiVersion: v1
kind: Service
metadata:
  name: ort-server-core
  namespace: {{ .Release.Namespace }}
  labels:
    app: ort-server-core
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.core.service.port }}
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: ort-server-core
