# Copyright (C) 2022 The ORT Server Authors (See <https://github.com/eclipse-apoapsis/ort-server/blob/main/NOTICE>)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0
# License-Filename: LICENSE

[versions]
# Gradle plugins
buildConfigPlugin = "6.0.10"
detektPlugin = "2.0.0-alpha.6"
gitSemverPlugin = "0.19.5"
koinCompilerPlugin = "1.1.0"
tinyJibPlugin = "0.4.0"
kotlinPlugin = "2.4.10"
kotlinxCoroutines = "1.11.0"
kotlinxSerialization = "1.11.0"
kspPlugin = "2.3.11"
mavenPublishPlugin = "0.37.0"

# Gradle dependencies
aedile = "3.0.4"
awsSdk = "1.8.41"
azureIdentity = "1.18.6"
azureMessagingServicebus = "7.17.20"
azureSecurityKeyvaultSecrets = "4.11.2"
azureStorageBlob = "12.35.1"
clikt = "5.1.0"
commonsText = "1.15.0"
exposed = "1.5.0"
flociTestcontainerVersion = "2.16.1"
flyway = "13.5.0"
hikari = "7.1.0"
hoplite = "2.9.0"
jsonSchemaValidator = "3.0.7"
kaml = "0.104.0"
keycloakTestcontainerVersion = "4.3.1"
koin = "4.2.2"
konform = "0.11.1"
kotest = "6.2.4"
kotestAssertionsKtor = "2.0.0"
kotlinResult = "2.3.1"
ktorOpenApi = "5.7.0"
ktorRateLimit = "3.5.2"
kubernetesClient = "27.0.0"
log4j = "2.26.1"
logback = "1.6.3"
micrometer = "1.17.1"
mockk = "1.14.11"
mordant = "3.1.0"
okio = "3.18.2"
postgres = "42.7.13"
springSecurityCrypto = "7.1.1"
qpidJmsClient = "2.11.0"
rabbitMq = "5.35.0"
schemaKenerator = "2.7.2"
slf4j = "2.0.19"
testContainers = "2.0.5"
typesafeConfig = "1.4.9"
wiremock = "3.13.2"

[plugins]
buildConfig = { id = "com.github.gmazzo.buildconfig", version.ref = "buildConfigPlugin" }
gitSemver = { id = "com.github.jmongard.git-semver-plugin", version.ref = "gitSemverPlugin" }
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlinPlugin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "kspPlugin" }
tinyJib = { id = "tel.schich.tinyjib", version.ref = "tinyJibPlugin" }

[libraries]
# These are Maven coordinates for Gradle plugins, which is necessary to use them in precompiled plugin scripts.
plugin-detekt = { module = "dev.detekt:detekt-gradle-plugin", version.ref = "detektPlugin" }
plugin-koinCompiler = { module = "io.insert-koin:koin-compiler-gradle-plugin", version.ref = "koinCompilerPlugin" }
plugin-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlinPlugin" }
plugin-mavenPublish = { module = "com.vanniktech:gradle-maven-publish-plugin", version.ref = "mavenPublishPlugin" }
plugin-tinyJib = { module = "tel.schich.tinyjib:tel.schich.tinyjib.gradle.plugin", version.ref = "tinyJibPlugin" }

aedile = { module = "com.sksamuel.aedile:aedile-core", version.ref = "aedile" }
azure-identity = { module = "com.azure:azure-identity", version.ref = "azureIdentity" }
azure-messaging-servicebus = { module = "com.azure:azure-messaging-servicebus", version.ref = "azureMessagingServicebus" }
azure-security-keyvault-secrets = { module = "com.azure:azure-security-keyvault-secrets", version.ref = "azureSecurityKeyvaultSecrets" }
azure-storage-blob = { module = "com.azure:azure-storage-blob", version.ref = "azureStorageBlob" }
clikt = { module = "com.github.ajalt.clikt:clikt", version.ref = "clikt" }
commons-text = { module = "org.apache.commons:commons-text", version.ref = "commonsText" }
exposed-core = { module = "org.jetbrains.exposed:exposed-core", version.ref = "exposed" }
exposed-dao = { module = "org.jetbrains.exposed:exposed-dao", version.ref = "exposed" }
exposed-jdbc = { module = "org.jetbrains.exposed:exposed-jdbc", version.ref = "exposed" }
exposed-json = { module = "org.jetbrains.exposed:exposed-json", version.ref = "exposed" }
exposed-kotlinDatetime = { module = "org.jetbrains.exposed:exposed-kotlin-datetime", version.ref = "exposed" }
flyway-core = { module = "org.flywaydb:flyway-core", version.ref = "flyway" }
flyway-postgresql = { module = "org.flywaydb:flyway-database-postgresql", version.ref = "flyway" }
hikari = { module = "com.zaxxer:HikariCP", version.ref = "hikari" }
hoplite-core = { module = "com.sksamuel.hoplite:hoplite-core", version.ref = "hoplite" }
hoplite-hocon = { module = "com.sksamuel.hoplite:hoplite-hocon", version.ref = "hoplite" }
jsonSchemaValidator = { module = "com.networknt:json-schema-validator", version.ref = "jsonSchemaValidator" }
kaml = { module = "com.charleskorn.kaml:kaml", version.ref = "kaml" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-ktor = { module = "io.insert-koin:koin-ktor", version.ref = "koin" }
koin-test = { module = "io.insert-koin:koin-test", version.ref = "koin" }
konform = { module = "io.konform:konform", version.ref = "konform" }
kotest-assertions-core = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
kotest-assertions-ktor = { module = "io.kotest.extensions:kotest-assertions-ktor", version.ref = "kotestAssertionsKtor" }
kotest-assertions-table = { module = "io.kotest:kotest-assertions-table", version.ref = "kotest" }
kotest-extensions-koin = { module = "io.kotest:kotest-extensions-koin", version.ref = "kotest" }
kotest-extensions-testcontainers = { module = "io.kotest:kotest-extensions-testcontainers", version.ref = "kotest" }
kotest-framework-engine = { module = "io.kotest:kotest-framework-engine", version.ref = "kotest" }
kotest-runner-junit5 = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }
kotlin-bom = { module = "org.jetbrains.kotlin:kotlin-bom", version.ref = "kotlinPlugin" }
kotlinResult = { module = "com.michael-bull.kotlin-result:kotlin-result", version.ref = "kotlinResult" }
kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutines" }
kotlinx-coroutines-slf4j = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-slf4j", version.ref = "kotlinxCoroutines" }
kotlinx-serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "kotlinxSerialization" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerialization" }
ktor-openApi = { module = "io.github.smiley4:ktor-openapi", version.ref = "ktorOpenApi" }
ktor-swaggerUi = { module = "io.github.smiley4:ktor-swagger-ui", version.ref = "ktorOpenApi" }
ktor-rateLimit = { module = "io.ktor:ktor-server-rate-limit-jvm", version.ref = "ktorRateLimit" }
kubernetes-client = { module = "io.kubernetes:client-java", version.ref = "kubernetesClient" }
kubernetes-clientApiFluent = { module = "io.kubernetes:client-java-api-fluent", version.ref = "kubernetesClient" }
log4jToSlf4j = { module = "org.apache.logging.log4j:log4j-to-slf4j", version.ref = "log4j" }
logback = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
micrometerRegistryGraphite = { module = "io.micrometer:micrometer-registry-graphite", version.ref = "micrometer" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
mordantCoroutines = { module =  "com.github.ajalt.mordant:mordant-coroutines", version.ref = "mordant" }
okio = { module = "com.squareup.okio:okio", version.ref = "okio" }
postgres = { module = "org.postgresql:postgresql", version.ref = "postgres" }
spring-security-crypto = { module = "org.springframework.security:spring-security-crypto", version.ref = "springSecurityCrypto" }
qpidJmsClient = { module = "org.apache.qpid:qpid-jms-client", version.ref = "qpidJmsClient" }
rabbitMqAmqpClient = { module = "com.rabbitmq:amqp-client", version.ref = "rabbitMq" }
s3 = { module = "aws.sdk.kotlin:s3", version.ref = "awsSdk" }
schemaKenerator-core = { module = "io.github.smiley4:schema-kenerator-core", version.ref = "schemaKenerator" }
schemaKenerator-reflection = { module = "io.github.smiley4:schema-kenerator-reflection", version.ref = "schemaKenerator" }
schemaKenerator-swagger = { module = "io.github.smiley4:schema-kenerator-swagger", version.ref = "schemaKenerator" }
slf4j = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
sqs = { module = "aws.sdk.kotlin:sqs", version.ref = "awsSdk" }
testContainers = { module = "org.testcontainers:testcontainers", version.ref = "testContainers" }
testContainers-floci = { module = "io.floci:testcontainers-floci", version.ref = "flociTestcontainerVersion" }
testContainers-keycloak = { module = "com.github.dasniko:testcontainers-keycloak", version.ref = "keycloakTestcontainerVersion" }
testContainers-postgresql = { module = "org.testcontainers:testcontainers-postgresql", version.ref = "testContainers" }
testContainers-rabbitMq = { module = "org.testcontainers:testcontainers-rabbitmq", version.ref = "testContainers" }
testContainers-vault = { module = "org.testcontainers:testcontainers-vault", version.ref = "testContainers" }
typesafeConfig = { module = "com.typesafe:config", version.ref = "typesafeConfig" }
wiremock = { module = "org.wiremock:wiremock", version.ref = "wiremock" }

[bundles]
flyway = ["flyway-core", "flyway-postgresql"]
schemaKenerator = ["schemaKenerator-core", "schemaKenerator-reflection", "schemaKenerator-swagger"]
