= Kubernetes Transport Implementation

This module provides an implementation of the transport abstraction layer using the
https://github.com/kubernetes-client/java/[Kubernetes Java Client].

== Synopsis

The Kubernetes transport abstraction layer exchanges messages via environment variables.
The sender creates a Kubernetes Job using the Kubernetes API, that runs the configured container image and sets the message content as environment variables.
The container started by the Kubernetes Job acts as the receiver and constructs the message from the environment variables.

== Configuration

In order to use this module, the `type` property in the transport configuration must be set to `kubernetes`.
For the sender part, a number of properties can be provided to configure the resulting pods as shown in the fragment
below:

[source]
----
endpoint {
    sender {
        type = "kubernetes"
        namespace = "namespace-inside-cluster"
        imageName = "image-to-run"
        imagePullPolicy = "Always"
        imagePullSecret = "my-secret"
        restartPolicy = ""
        backoffLimit = 5
        commands = "/bin/sh"
        args = "-c java my.pkg.MyClass"
        mountSecrets = "server-secrets->/mnt/secrets server-certificates->/mnt/certificates"
        annotationVariables = "ANNOTATION_VAR1, ANNOTATION_VAR2"
    }
}
----

The properties have the following meaning:

.Supported configuration properties
[cols="1,3,1",options=header]
|===
|Property |Description |Default

|namespace
|The namespace inside the Kubernetes cluster, in which the job will be created.
|none

|imageName
|The full name of the container image from which the pod is created, including the tag name.
|none

|imagePullPolicy
|Defines the https://kubernetes.io/docs/concepts/containers/images/#image-pull-policy[pull policy] for the container
image, one of `IfNotPresent`, `Always`, or `Never`.
|`Never`

|imagePullSecret
|The name of the secret to be used to connect to the container registry when pulling the container image. This is
needed when using private registries that require authentication.
|empty

|restartPolicy
|The https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#restart-policy[restart policy] for the
container, one of `Always`, `OnFailure`, or `Never`.
|`OnFailure`

|backoffLimit
|Defines the https://kubernetes.io/docs/concepts/workloads/controllers/job/#pod-backoff-failure-policy[backup failure policy]
for the job to be created. This is the number of retries for failed pods attempted by Kubernetes before it considers
the job as failed.
|2

|commands
|The commands to be executed in the container. This can be used to overwrite the container's default command and
corresponds to the `command` property in the
https://kubernetes.io/docs/tasks/inject-data-application/define-command-argument-container/[Kubernetes pod configuration].
Here a string can be specified. In order to obtain the array with commands expected by Kubernetes, the string is split
at whitespaces, unless the whitespace occurs in double quotes.
|empty

|args
|The arguments to be passed to the container's start command. This corresponds to the `args` property in the
https://kubernetes.io/docs/tasks/inject-data-application/define-command-argument-container/[Kubernetes pod configuration].
It is confusing that Kubernetes treats both properties, `command` and `args`, as arrays. In most examples, a single
string is used as `command`, while multiple arguments can be provided in the `args` array. Analogously to the
`commands` property, the string provided here is split at whitespaces to obtain the arguments. If a single argument
contains whitespaces, it needs to be surrounded by double quotes.
|empty

|mountSecrets
|With this property, it is possible to mount the contents of Kubernetes
https://kubernetes.io/docs/concepts/configuration/secret/[secrets] as files into the resulting pod. The string is
interpreted as a sequence of mount declarations separated by whitespace. Each mount declaration has the form
_secret->mountPath_, where _secret_ is the name of a secret, and _mountPath_ is a path in the container where the
content of the secret should be made available. At this path, for each key of the secret a file is created whose
content is the value of the key. To achieve this, the Kubernetes Transport implementation generates corresponding
`volume` and `volumeMount` declarations in the pod configuration. This mechanism is useful not only for secrets but
also for other kinds of external data that should be accessible from a pod, for instance custom certificates.
|empty

|annotationVariables
a|It is often useful or necessary to declare specific annotations for the jobs that are created by the Kubernetes Transport implementation. This can be used for instance for documentation purposes, to group certain jobs, or to request specific services from the infrastructure. Since there can be an arbitrary number of annotations that also might become complex, it is difficult to use a single configuration property to define all annotations at once. (And using a dynamic set of configuration properties does not work well either with the typical approach configuration is read in ORT Server.)

To deal with these issues, the implementation introduces a level of indirection: The _annotationVariables_ property does not contain the definitions for annotations itself, but only lists the names of environment variables - separated by comma - that declare annotations. Each referenced environment variable must have a value of the form `key=value`. The _key_ becomes the key of the annotation, the _value_ its value.

As a concrete example, if _annotationVariables_ has the value

 annotationVariables = "VAR1, VAR2"

and there are corresponding environment variables:

 VAR1=annotation1=value1
 VAR2=annotation2=value2

then the Kubernetes Transport implementation will produce a job declaration containing the following fragment:

[source,yaml]
----
template:
  metadata:
    annotations:
      annotation1: value1
      annotation2: value2
----

If variables are referenced that do not exist or do not contain an equals ('=') character in their value to separate the key from the value, a warning is logged, and those variables are ignored.
|empty
|===

NOTE: The receiver part does not need any specific configuration settings except for the transport type itself.

== Inheritance of environment variables
Per default, when creating a new job, the `KubernetesMessageSender` passes all environment variables defined for the
current pod to the specification of the new job. That way common variables like service credentials can be shared
between pods.

A problem can arise though if there are name clashes with environment variables, e.g. if the new job requires a
different value in a variable than the current pod. To address such problems, the Kubernetes transport protocol
supports a simple mapping mechanism for variable names that start with a prefix derived from the target endpoint:
When setting up the environment variables for the new job it checks for variables whose name starts with the prefix
name of the target endpoint in capital letters followed by an underscore. This prefix is then removed from the
variable in the environment of the new job.

For instance, in order to set the `HOME` variable for the Analyzer worker to a specific value, define a variable
`ANALYZER_HOME` in the Orchestrator pod. When then a new Analyzer job is created, its `HOME` variable get initialized
from the value of the `ANALYZER_HOME` variable. An existing `HOME` variable in the Orchestrator pod will not conflict
with this other value.
