-- This migration script integrates the issues generated by the Analyzer into the ORT run issues table.

INSERT INTO ort_runs_issues
("ort_run_id", "issue_id", "identifier_id", "worker", "timestamp")
SELECT
  aj.ort_run_id,
  i.id,
  ii.identifier_id,
  'analyzer',
  i."timestamp"
FROM analyzer_runs ar
INNER JOIN analyzer_jobs aj ON ar.analyzer_job_id = aj.id
INNER JOIN analyzer_runs_identifiers_issues arii ON arii.analyzer_run_id = ar.id
INNER JOIN identifiers_issues ii ON arii.identifier_issue_id = ii.id
INNER JOIN issues i ON ii.issue_id = i.id;

DROP TABLE analyzer_runs_identifiers_issues;
