-- This migration script integrates the issues generated by the Advisor into the ORT run issues table.

INSERT INTO ort_runs_issues
("ort_run_id", "issue_id", "identifier_id", "worker", "timestamp")
SELECT
  aj.ort_run_id,
  i.id,
  ari.identifier_id,
  'advisor',
  i."timestamp"
FROM advisor_runs ar
INNER JOIN advisor_jobs aj ON ar.advisor_job_id = aj.id
INNER JOIN advisor_runs_identifiers ari ON ari.advisor_run_id = ar.id
INNER JOIN advisor_results ar2 on ar2.advisor_run_identifier_id = ari.id
INNER JOIN advisor_results_issues ari2 ON ari2.advisor_result_id = ar2.id
INNER JOIN issues i ON ari2.issue_id = i.id;

DROP TABLE advisor_results_issues;
