-- This migration script integrates the issues generated by the Scanner into the ORT run issues table.
-- In contrast to the scripts for the Analyzer and Advisor issues, this is more tricky because the issues are
-- assigned to scan summaries, and there is no direct link to a package the scan summary belongs to. Therefore, the
-- match is made via the provenance which can point either to a source code artifact or a VCS repository.

-- Handle scanner issues for artifact provenances.
INSERT INTO ort_runs_issues
("ort_run_id", "issue_id", "identifier_id", "worker", "timestamp")
SELECT
  sj.ort_run_id,
  i.id,
  scan_result_identifiers.identifier_id,
  'scanner',
  i."timestamp"
FROM scan_results sr
INNER JOIN scan_summaries ss on sr.scan_summary_id = ss.id
INNER JOIN scanner_runs_scan_results srsr on srsr.scan_result_id = sr.id
INNER JOIN scanner_runs sr2 on srsr.scanner_run_id = sr2.id
INNER JOIN scanner_jobs sj on sr2.scanner_job_id = sj.id
INNER JOIN scan_summaries_issues ssi on ssi.scan_summary_id = ss.id
INNER JOIN issues i on ssi.issue_id = i.id
INNER JOIN (
  SELECT
    sr.id AS scan_result_id,
    artifact_provenances.identifier_id,
    artifact_provenances.artifact_id
  FROM
    scan_results sr,
    (SELECT *
    FROM package_provenances pp
    INNER JOIN remote_artifacts ra on pp.artifact_id = ra.id
    ) AS artifact_provenances
  WHERE
    sr.artifact_url = artifact_provenances.url
    AND sr.artifact_hash = artifact_provenances.hash_value
    AND sr.artifact_hash_algorithm = artifact_provenances.hash_algorithm
) scan_result_identifiers on scan_result_identifiers.scan_result_id = sr.id;

-- Handle scanner issues for VCS provenances.
INSERT INTO ort_runs_issues
("ort_run_id", "issue_id", "identifier_id", "worker", "timestamp")
SELECT
  sj.ort_run_id,
  i.id, 
  scan_result_identifiers.identifier_id,
  'scanner',
  i."timestamp"
FROM scan_results sr
INNER JOIN scan_summaries ss on sr.scan_summary_id = ss.id
INNER JOIN scanner_runs_scan_results srsr on srsr.scan_result_id = sr.id
INNER JOIN scanner_runs sr2 on srsr.scanner_run_id = sr2.id  
INNER JOIN scanner_jobs sj on sr2.scanner_job_id = sj.id  
INNER JOIN scan_summaries_issues ssi on ssi.scan_summary_id = ss.id
INNER JOIN issues i on ssi.issue_id = i.id
INNER JOIN (
  SELECT
    sr.id AS scan_result_id,
    vcs_provenances.identifier_id
  FROM 
    scan_results sr,  
    (SELECT *
    FROM package_provenances pp
    INNER JOIN vcs_info vi on pp.vcs_id = vi.id
    ) AS vcs_provenances
  WHERE
    sr.vcs_type = vcs_provenances.type
    AND sr.vcs_url = vcs_provenances.url
    AND sr.vcs_revision = vcs_provenances.revision
    AND vcs_provenances."path" = ''
) scan_result_identifiers on scan_result_identifiers.scan_result_id = sr.id;
