@startuml

component ApiV1 [
<b>API v1</b>
API model,
mappings, ...
]

component ApiV2 [
<b>API v2</b>
API model,
mappings, ...
]

component ApiClientV1 [
<b>API Client v1</b>
MP Ktor Client
]

component ApiClientV2 [
<b>API Client v2</b>
MP Ktor Client
]

component Clients [
<b>Clients</b>
Keycloak, ...
]

component Core [
<b>Core</b>
DI, Routing, ...
]

component Dao [
<b>DAO</b>
Database access
]

component Frontend [
<b>Frontend</b>
Kotlin/JS
]

component Model [
<b>Model</b>
Model classes,
interfaces
]

component Orchestrator [
<b>Orchestrator</b>
Job orchestration
]

component Services [
<b>Services</b>
Business Logic,
transactions, ...
]

component Transport [
<b>Transport</b>
jobs, messaging
]

component Workers [
<b>Workers</b>
Analyzer, Scanner, ...
]

ApiV1 ..> Services
ApiV2 ..> Services
ApiClientV1 ..> ApiV1
ApiClientV2 ..> ApiV2
Core ..> ApiV1
Core ..> ApiV2
Core ..> Orchestrator
Core ..> Transport
Dao ..> Model
Frontend <.. Core
Frontend ..> ApiClientV1
Orchestrator ..> Dao
Orchestrator ..> Transport
Services ..> Clients
Services ..> Dao
Services ..> Transport
Transport..>Model
Workers <..> Core : API Calls, Service Bus
Workers ..> Transport

@enduml
