= Gradle Modules

The document explains the Gradle module structure and the dependencies between the modules.
Note that the graph below shows the hierarchy of the modules and does not necessarily reflect how exactly module dependencies are implemented in Gradle.

[plantuml,gradle_modules,svg]
----
include::gradle_modules.puml[]
----

== Module Descriptions

=== Model

The model module contains the internally used class and interface definitions.

=== DAO

The DAO module contains all code related to database access, for example database specific repository implementations.
A repository only has to be implemented for an https://martinfowler.com/bliki/DDD_Aggregate.html[aggregate root] and not for every table.
An aggregate root is the most important entity object, which encapsulates entity/value objects.
Because of this only the business model classes representing aggregate roots have a property for the database id.
For all other classes this is considered an implementation detail of the DAO layer.
Note that we are not strict with regard to DDD and allow multiple repositories to access the same tables, for example both analyzer and scanner runs contain an environment and store this information in the same tables.

=== Clients

The client modules contain independent clients, for example for Keycloak, that can be used by the services.

=== Services

The services module contains the business logic.

=== Core

The core module contains the Ktor backend including route definitions, dependency injection, and configuration.
It is also responsible for authentication.

=== API

The API modules contain the API model for different API versions.
They are responsible for mapping the internal model to the API model.
Different versions of the API can be implemented to provide a stable API and backward compatibility.
Also, the route definitions might be moved to the API modules later on.

=== API Client

The API client modules are supposed to be Kotlin multiplatform implementations of the API which can be published to be used by third-party tools.
However, since the core also provides an OpenAPI specification it might turn out to be more feasible to generate clients from that.

=== Frontend

The frontend is a Kotlin/JS application hosted by the core which uses an API client to access the API.
This is only one option to provide a frontend, it might also be decided to implement it with another language like TypeScript.

=== Workers

The worker modules contain code that run the individual ORT tools, like the analyzer.
They run independently of the backend to process jobs and communicate with the backend for example via API calls or a service bus.

=== Transport

Modules under _transport_ implement different approaches for the message exchange between core, services, and workers.
The main goal here is to become independent of the underlying infrastructure, so that the server could be deployed in different environments.
For instance, there can be implementations making use of different messaging products.
Also, the scheduling of tasks from the Orchestrator to the workers is considered a special case of message exchange and is therefore covered by this abstraction layer.
