= Gradle Modules

The document explains the Gradle module structure and the dependencies between the modules. Note that the graph below
shows the hierarchy of the modules and does not necessarily reflect how exactly module dependencies are implemented in
Gradle.

[plantuml, gradle_modules, svg]
----
include::gradle_modules.puml[]
----

== Module Descriptions

=== Model

The model module contains the internally used class and interface definitions.

=== DAO

The DAO module contains all code related to database access, for example database specific repository implementations.

=== Clients

The client modules contain independent clients, for example for Keycloak, that can be used by the services.

=== Services

The services module contains the business logic.

=== Core

The core module contains the Ktor backend including route definitions, dependency injection, and configuration. It is
also responsible for authentication.

=== API

The API modules contain the API model for different API versions. They are responsible for mapping the internal model to
the API model. Different versions of the API can be implemented to provide a stable API and backward compatibility.
Also, the route definitions might be moved to the API modules later on.

=== API Client

The API client modules are supposed to be Kotlin multiplatform implementations of the API which can be published to be
used by third-party tools. However, since the core also provides an OpenAPI specification it might turn out to be more
feasible to generate clients from that.

=== Frontend

The frontend is a Kotlin/JS application hosted by the core which uses an API client to access the API. This is only one
option to provide a frontend, it might also be decided to implement it with another language like TypeScript.

=== Workers

The worker modules contain code that run the individual ORT tools, like the analyzer. They run independently of the
backend to process jobs and communicate with the backend for example via API calls or a service bus.
