{
 "title": "ORT Run Component Logs",
 "description": "With this dashboard, you can filter with the run ID and log levels for each individual component (orchestrator, core, config_worker, analyzer_worker, advisor_worker, scanner_worker, evaluator_worker and reporter_worker).",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   { "name": "run_id", "label": "Run ID", "query": "60" },
   { "name": "orchestrator_log_levels", "label": "Orchestrator", "query": "ERROR,WARN,INFO,DEBUG,TRACE" },
   { "name": "core_log_levels", "label": "Core", "query": "ERROR,WARN,INFO,DEBUG,TRACE" },
   { "name": "config_log_levels", "label": "Config", "query": "ERROR,WARN,INFO,DEBUG,TRACE" },
   { "name": "analyzer_log_levels", "label": "Analyzer", "query": "ERROR,WARN,INFO,DEBUG,TRACE" },
   { "name": "advisor_log_levels", "label": "Advisor", "query": "ERROR,WARN,INFO,DEBUG,TRACE" },
   { "name": "scanner_log_levels", "label": "Scanner", "query": "ERROR,WARN,INFO,DEBUG,TRACE" },
   { "name": "evaluator_log_levels", "label": "Evaluator", "query": "ERROR,WARN,INFO,DEBUG,TRACE" },
   { "name": "reporter_log_levels", "label": "Reporter", "query": "ERROR,WARN,INFO,DEBUG,TRACE" }
  ]
 },
 "panels": [
  {
   "title": "Orchestrator",
   "type": "logs",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{component=\"orchestrator\"} | logfmt |~ `(?P<level>level=($orchestrator_log_levels))` | regexp `message=\"(?P<msg>[^\"]+)\"` | line_format `{{.time}} {{.msg}}` | label_format level=level_extracted"
    }
   ]
  },
  {
   "title": "Core",
   "type": "logs",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{component=\"core\"} | logfmt |~ `(?P<level>level=($core_log_levels))` | regexp `message=\"(?P<msg>[^\"]+)\"` | line_format `{{.time}} {{.msg}}` | label_format level=level_extracted"
    }
   ]
  },
  {
   "title": "Config",
   "type": "logs",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{component=\"config-worker\"} | logfmt |~ `(?P<run_id>ortRunId=$run_id)` |~ `(?P<level>level=($config_log_levels))` | regexp `message=\"(?P<msg>[^\"]+)\"` | line_format `{{.time}} {{.msg}}` | label_format level=level_extracted"
    }
   ]
  },
  {
   "title": "Analyzer",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{component=\"analyzer-worker\"} | logfmt |~ `(?P<run_id>ortRunId=$run_id)` |~ `(?P<level>level=($analyzer_log_levels))` | regexp `message=\"(?P<msg>[^\"]+)\"` | line_format `{{.time}} {{.msg}}` | label_format level=level_extracted"
    }
   ]
  },
  {
   "title": "Advisor",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{component=\"advisor-worker\"} | logfmt |~ `(?P<run_id>ortRunId=$run_id)` |~ `(?P<level>level=($advisor_log_levels))` | regexp `message=\"(?P<msg>[^\"]+)\"` | line_format `{{.time}} {{.msg}}` | label_format level=level_extracted"
    }
   ]
  },
  {
   "title": "Scanner",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{component=\"scanner-worker\"} | logfmt |~ `(?P<run_id>ortRunId=$run_id)` |~ `(?P<level>level=($scanner_log_levels))` | regexp `message=\"(?P<msg>[^\"]+)\"` | line_format `{{.time}} {{.msg}}` | label_format level=level_extracted"
    }
   ]
  },
  {
   "title": "Evaluator",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{component=\"evaluator-worker\"} | logfmt |~ `(?P<run_id>ortRunId=$run_id)` |~ `(?P<level>level=($evaluator_log_levels))` | regexp `message=\"(?P<msg>[^\"]+)\"` | line_format `{{.time}} {{.msg}}` | label_format level=level_extracted"
    }
   ]
  },
  {
   "title": "Reporter",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{component=\"reporter-worker\"} | logfmt |~ `(?P<run_id>ortRunId=$run_id)` |~ `(?P<level>level=($reporter_log_levels))` | regexp `message=\"(?P<msg>[^\"]+)\"` | line_format `{{.time}} {{.msg}}` | label_format level=level_extracted"
    }
   ]
  }
 ]
}