{
 "title": "ORT Run & Job Status",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "job",
    "query": "analyzer,advisor,scanner,evaluator,reporter"
   }
  ]
 },
 "panels": [
  { "title": "ORT Runs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "ORT Runs: Active",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 1 },
   "targets": [
    {
     "target": "aliasByMetric(ort-server-core.runs.status.created)"
    },
    {
     "target": "aliasByMetric(ort-server-core.runs.status.active)"
    }
   ]
  },
  {
   "title": "ORT Runs: Finished",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 3, "x": 10, "y": 1 },
   "targets": [
    {
     "target": "aliasByMetric(ort-server-core.runs.status.finished)"
    }
   ]
  },
  {
   "title": "ORT Runs: Finished with Issues",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 3, "x": 13, "y": 1 },
   "targets": [
    {
     "target": "aliasByMetric(ort-server-core.runs.status.finished_with_issues)"
    }
   ]
  },
  {
   "title": "ORT Runs: Failed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 3, "x": 16, "y": 1 },
   "targets": [
    {
     "target": "aliasByMetric(ort-server-core.runs.status.failed)"
    }
   ]
  },
  { "title": "$job jobs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 }, "repeat": "job" },
  {
   "title": "$job jobs: active",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 10 },
   "targets": [
    {
     "target": "aliasByMetric(ort-server-core.jobs.$job.status.created)"
    },
    {
     "target": "aliasByMetric(ort-server-core.jobs.$job.status.scheduled)"
    },
    {
     "target": "aliasByMetric(ort-server-core.jobs.$job.status.running)"
    }
   ]
  },
  {
   "title": "$job jobs: finished",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 3, "x": 10, "y": 10 },
   "targets": [
    {
     "target": "aliasByMetric(ort-server-core.jobs.$job.status.finished)"
    }
   ]
  },
  {
   "title": "$job jobs: finished with issues",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 3, "x": 13, "y": 10 },
   "targets": [
    {
     "target": "aliasByMetric(ort-server-core.jobs.$job.status.finished_with_issues)"
    }
   ]
  },
  {
   "title": "$job jobs: failed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 3, "x": 16, "y": 10 },
   "targets": [
    {
     "target": "aliasByMetric(ort-server-core.jobs.$job.status.failed)"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 19, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "seriesByTag('name=ort-server-core.jobs.$job.duration', 'metricattribute=mean')"
    },
    {
     "target": "movingAverage(seriesByTag('name=ort-server-core.jobs.$job.duration', 'metricattribute=mean'), '10min')"
    },
    {
     "target": "movingAverage(seriesByTag('name=ort-server-core.jobs.$job.duration', 'metricattribute=max'), '10min')"
    }
   ]
  }
 ]
}