name: "Free Disk Space"
description: "Remove unneeded preinstalled Docker images and software to free disk space."
author: "The ORT Server Authors"

runs:
  using: "composite"

  steps:
  - name: Print Disk Space
    shell: bash
    run: df -h
  - name: Get Size of Installed Tools
    if: ${{ false }} # Can be enabled if the 'Remove Unneeded Tools' step below needs to be updated.
    shell: bash
    run: |
      sudo du -hsc /usr/lib/*
      sudo du -hsc /usr/local/*
      sudo du -hsc /usr/local/lib/*
      sudo du -hsc /usr/local/share/*
      sudo du -hsc /usr/share/*
  - name: Remove Unneeded Tools
    shell: bash
    run: |
      sudo rm -rf /usr/lib/dotnet
      sudo rm -rf /usr/lib/firefox
      sudo rm -rf /usr/local/aws-cli
      sudo rm -rf /usr/local/aws-sam-cli
      sudo rm -rf /usr/local/lib/android
      sudo rm -rf /usr/local/lib/node_modules
      sudo rm -rf /usr/local/share/chromium
      sudo rm -rf /usr/local/share/powershell
      sudo rm -rf /usr/local/share/vcpkg
      sudo rm -rf /usr/share/az_12.1.0
      sudo rm -rf /usr/share/kotlinc
      sudo rm -rf /usr/share/mecab
      sudo rm -rf /usr/share/miniconda
      sudo rm -rf /usr/share/ri
      sudo rm -rf /usr/share/swift
      sudo rm -rf /usr/share/vim
  - name: Print Disk Space
    shell: bash
    run: df -h
