### Get all vulnerabilities for an ORT run
GET {{host}}/runs/1/vulnerabilities
Authorization: Bearer {{$auth.token("keycloak")}}

### Get all packages for an ORT run
GET {{host}}/runs/1/packages
Authorization: Bearer {{$auth.token("keycloak")}}

### Get rule violations for an ORT run
GET {{host}}/runs/1/rule-violations?resolved=false
Authorization: Bearer {{$auth.token("keycloak")}}
