/*
 * Copyright (C) 2026 The ORT Server Authors (See <https://github.com/eclipse-apoapsis/ort-server/blob/main/NOTICE>)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * SPDX-License-Identifier: Apache-2.0
 * License-Filename: LICENSE
 */

import type { JobConfigurations } from '@/api';
import {
  formatRunConfigurationDiffPath,
  getValueAtPath,
  pathStartsWith,
} from './path';
import type {
  RunConfigurationDiffAddedEntry,
  RunConfigurationDiffEntry,
  RunConfigurationDiffPathSegment,
  RunConfigurationDiffRemovedEntry,
} from './types';

/**
 * Paths to string arrays whose order is not meaningful for this UI diff.
 *
 * The API schema tells us which fields are arrays, but it does not tell us
 * whether the order of an array changes the meaning of the configuration.
 * `microdiff` compares arrays by index, so inserting one item into an
 * unordered list would otherwise make every following item look modified.
 *
 * Keep this list limited to fields where the values are selected names,
 * formats, addresses, or groups and where users care about membership rather
 * than position. Arrays not listed here remain order-sensitive.
 */
export const unorderedStringListPaths: RunConfigurationDiffPathSegment[][] = [
  ['advisor', 'advisors'],
  ['analyzer', 'disabledPackageManagers'],
  ['analyzer', 'enabledPackageManagers'],
  ['notifier', 'recipientAddresses'],
  ['reporter', 'assetDirectoriesGroups'],
  ['reporter', 'assetFilesGroups'],
  ['reporter', 'formats'],
  ['scanner', 'projectScanners'],
  ['scanner', 'scanners'],
];

const isStringArray = (value: unknown): value is string[] =>
  Array.isArray(value) && value.every((entry) => typeof entry === 'string');

/**
 * Check whether a configured unordered list path exists as a string array in
 * both configurations. If either side is missing or has another type,
 * `microdiff` should handle the change normally.
 */
const isUnorderedStringListPath = (
  baseConfig: JobConfigurations,
  comparedConfig: JobConfigurations,
  path: RunConfigurationDiffPathSegment[]
): boolean =>
  isStringArray(getValueAtPath(baseConfig, path)) &&
  isStringArray(getValueAtPath(comparedConfig, path));

/**
 * Detect entries generated by index-based array comparison for unordered
 * string lists. These entries are removed and replaced with added / removed
 * value entries to avoid noisy churn when an item is inserted in the middle.
 */
export const isEntryForUnorderedStringList = (
  entry: RunConfigurationDiffEntry,
  baseConfig: JobConfigurations,
  comparedConfig: JobConfigurations
): boolean =>
  unorderedStringListPaths.some(
    (path) =>
      isUnorderedStringListPath(baseConfig, comparedConfig, path) &&
      pathStartsWith(entry.pathSegments, path)
  );

const createStringListEntry = (
  pathSegments: RunConfigurationDiffPathSegment[],
  status: 'added' | 'removed',
  value: string,
  index: number
): RunConfigurationDiffAddedEntry | RunConfigurationDiffRemovedEntry => {
  const path = [...pathSegments, index];

  return status === 'added'
    ? {
        status,
        path: formatRunConfigurationDiffPath(path),
        pathSegments: path,
        newValue: value,
      }
    : {
        status,
        path: formatRunConfigurationDiffPath(path),
        pathSegments: path,
        oldValue: value,
      };
};

/**
 * Compare a string array as an unordered list. The returned entries describe
 * only values that were added or removed; order-only changes are ignored.
 */
export const createUnorderedStringListDiffEntries = (
  pathSegments: RunConfigurationDiffPathSegment[],
  baseConfig: JobConfigurations,
  comparedConfig: JobConfigurations
): RunConfigurationDiffEntry[] => {
  const baseValue = getValueAtPath(baseConfig, pathSegments);
  const comparedValue = getValueAtPath(comparedConfig, pathSegments);

  if (!isStringArray(baseValue) || !isStringArray(comparedValue)) {
    return [];
  }

  const baseValues = new Set(baseValue);
  const comparedValues = new Set(comparedValue);

  return [
    ...comparedValue.flatMap((value, index) =>
      baseValues.has(value)
        ? []
        : [createStringListEntry(pathSegments, 'added', value, index)]
    ),
    ...baseValue.flatMap((value, index) =>
      comparedValues.has(value)
        ? []
        : [createStringListEntry(pathSegments, 'removed', value, index)]
    ),
  ];
};
