# Default values for ort-server.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

#######################################################
# These variables are defined in HashiCorp sub-charts.
#######################################################

vault:
  server:
    dev:
      enabled: true
      devRootToken: admin
  ui:
    enabled: true
    serviceType: LoadBalancer

#######################################################
# These variables are defined in Bitnami sub-charts.
#######################################################

keycloak:
  image:
    tag: 26.2.0
  extraVolumes:
    - name: keycloak-init-volume
      persistentVolumeClaim:
        claimName: "{{ tpl .Release.Name . }}-keycloak-pvc"
  extraVolumeMounts:
    - mountPath: /opt/keycloak_init/
      name: keycloak-init-volume
  auth:
    adminUser: "admin"
    adminPassword: "admin"
  service:
    http:
      enabled: true
    ports:
      http: 8081
      # Unfortunately HTTPS does not seem to be working. The server does not provide any certificate:
      # openssl s_client -connect keycloak:8082
      # -> SSL handshake has read 0 bytes and written 311 bytes
      https: 8082
  tls:
    enabled: true
    autoGenerated: true
  livenessProbe:
    initialDelaySeconds: 600
  postgresql:
    auth:
      database: ort_server
    primary:
      service:
        type: "LoadBalancer"
        # Unfortunately, using a different port is not supported. See https://github.com/bitnami/charts/issues/13661.
        ports:
          postgresql: 5432
      persistence:
        existingClaim: "{{ tpl .Release.Name . }}-postgres-pvc"
      pgHbaConfiguration: |
        # TYPE      DATABASE        USER    ADDRESS         METHOD
        local       all             all                     trust
        host        all             all     127.0.0.1/0     trust
        host        all             all     ::1/128         trust
    volumePermissions:
      enabled: true
rabbitmq:
  service:
    type: "LoadBalancer"
    ports:
      amqp: "5672"
      amqpTls: "5671"
      manager: "15672"
  enabled: true
  auth:
    username: admin
    password: admin
  loadDefinition:
    enabled: true
    existingSecret: rabbitmq-load-definition
  extraConfiguration: |
    load_definitions = /app/load_definition.json

#######################################################
# These variables are defined for ORT-Server chart.
#######################################################

ort_server:
  postgres:
    ## @param database.size The storage size to allocate for the database.
    size: 1Gi

    ## Location, in the cluster, where the database should be stored. This will be made available to the container with
    ## a 'hostPath' volume mount.
    ## You can verify the location in the cluster with `minikube ssh`. Please note that other locations could not
    ## survive cluster restarts (https://minikube.sigs.k8s.io/docs/handbook/persistent_volumes/).
    ## Additionally, you can mount a directory of the host with `minikube mount` to this location.
    location: "/data/postgres-pv"
    databaseSchema: "ort_server"
  keycloak:
    ## Location, in the cluster, where Keycloak initialization script is available. This will be made available to the
    ## container with a 'hostPath' volume mount.
    ## You can verify the location in the cluster with `minikube ssh`.
    ## Additionally, you can mount a directory of the host with `minikube mount` to this location.
    init_location: "/data/init-keycloak"
  artemis:
    enabled: false
    user: "admin"
    password: "admin"
    openWirePort: 61616
    managementConsolePort: 8161
  core:
    port: 8080
  orchestrator:
    # The queue for messages the Orchestrator will receive from the OrchestratorService (Core module).
    queueName: "orchestrator_queue"
