@startuml

entity CREDENTIAL {
* id: SERIAL
--
* name: VARCHAR(256)
description: TEXT
* value: TEXT
fkOrganization: VARCHAR(256)
fkProduct: VARCHAR(256)
fkRepository: INT
}

entity MAVEN_CREDENTIAL_MAPPING {
* id: SERIAL
--
* fkCredential: INT
fkOrganization: VARCHAR(256)
fkProduct: VARCHAR(256)
fkRepository: INT
* alias: VARCHAR(128)
* type: VARCHAR(32)
}

entity NPM_REGISTRY {
* id: SERIAL
--
fkOrganization: VARCHAR(256)
fkProduct: VARCHAR(256)
fkRepository: INT
* url: VARCHAR(256)
scope: VARCHAR(128)
* alwaysAuth: BOOL
}

entity NPMRC_CREDENTIAL_MAPPING {
* id: SERIAL
--
* fkCredential: INT
fkOrganization: VARCHAR(256)
fkProduct: VARCHAR(256)
fkRepository: INT
* fkRegistry: INT
* type: VARCHAR(32)
}

entity ENV_CREDENTIAL_MAPPING {
* id: SERIAL
--
* fkCredential: INT
fkOrganization: VARCHAR(256)
fkProduct: VARCHAR(256)
fkRepository: INT
variableName: VARCHAR(256)
}

NPMRC_CREDENTIAL_MAPPING::fkRegistry -- NPM_REGISTRY::id

MAVEN_CREDENTIAL_MAPPING::fkCredential -- CREDENTIAL::id
NPMRC_CREDENTIAL_MAPPING::fkCredential -- CREDENTIAL::id
ENV_CREDENTIAL_MAPPING::fkCredential -- CREDENTIAL::id

@enduml
