@startuml

entity ORT_RUN {
<<from result_shared>>
* id: SERIAL
}

entity PACKAGE_PROGRESS {
* id: SERIAL
--
* fkRun: INT
* fkPackage: INT
* startTime: TIMESTAMP
endTime: TIMESTAMP
}

entity PACKAGE_PROGRESS_STEP {
* id: SERIAL
--
* fkProgress: INT
* step: VARCHAR(32)
* endTime: TIMESTAMP
}

entity PROJECT_PROGRESS {
* id: SERIAL
--
* fkRun: INT
* fkProject: INT
* startTime: TIMESTAMP
endTime: TIMESTAMP
}

entity PROJECT_PROGRESS_STEP {
* id: SERIAL
--
* fkProgress: INT
* step: VARCHAR(32)
* endTime: TIMESTAMP
}

entity RUN_PROGRESS {
* id: SERIAL
--
* fkRun: INT
* startTime: TIMESTAMP
analyzerEndTime: TIMESTAMP
endTime: TIMESTAMP
}

PACKAGE_PROGRESS::fkRun -- ORT_RUN::id
PACKAGE_PROGRESS_STEP::fkProgress -- PACKAGE_PROGRESS::id

PROJECT_PROGRESS::fkRun -- ORT_RUN::id
PROJECT_PROGRESS_STEP::fkProgress -- PROJECT_PROGRESS::id

RUN_PROGRESS::fkRun -- ORT_RUN::id

@enduml
