@startuml

entity VCS_TYPE {
* id: SERIAL
--
* name: VARCHAR(128)
}

entity VCS_REPOSITORY {
* id: SERIAL
--
* fkType: INT
* url: VARCHAR(256)
}

entity NESTED_VCS_REPOSITORY {
* id: SERIAL
--
* fkRun: INT
* path: VARCHAR(256)
* vcsRepository: INT
* vcsRevision: VARCHAR(128)
* vcsPath: VARCHAR(256)
}

entity LABEL {
* id: SERIAL
--
* fkRun: INT
* key: VARCHAR(128)
* value: TEXT
}

entity ENVIRONMENT {
* id: SERIAL
--
* ortVersion: VARCHAR(64)
* javaVersion: VARCHAR(64)
* os: VARCHAR(32)
* processors: INT
* maxMemory: INT
}

entity ENVIRONMENT_VARIABLE {
* id: SERIAL
--
* fkEnvironment: INT
* name: VARCHAR(256)
* value: VARCHAR(256)
}

entity ORT_ISSUE {
*id: SERIAL
--
* timestamp: TIMESTAMP
* source: VARCHAR(64)
* message: VARCHAR(256)
* severity: INT
}

entity ORT_RUN {
* id: SERIAL
--
* vcsRepository: INT
* vcsRevision: VARCHAR(128)
* vcsPath: VARCHAR(256)
* vcsProcessedRepository: INT
* vcsProcessedRevision: VARCHAR(128)
* vcsProcessedPath: VARCHAR(256)
* config: jsonb
}

VCS_REPOSITORY::fkType -- VCS_TYPE::id

NESTED_VCS_REPOSITORY::vcsRepository -- VCS_REPOSITORY::id
NESTED_VCS_REPOSITORY::fkRun -- ORT_RUN::id

LABEL::fkRun -- ORT_RUN::id

ENVIRONMENT_VARIABLE::fkEnvironment -- ENVIRONMENT::id

ORT_RUN::vcsRepository -- VCS_REPOSITORY::id
ORT_RUN::vcsProcessedRepository -- VCS_REPOSITORY::id

@enduml
