= API Design

This document introduces the general API design of the ORT server, to provide a guideline when implementing new API endpoints.
The actual implemented API will be documented using https://www.openapis.org[OpenAPI].

The use case for this design will focus on two entities. `Organizations` and `Products`: A product is always assigned to an organization, and an organization hosts multiple projects.

== Organizations

*Create Organizations*

----
POST /organizations

Request
{
  "name": "Organization's name",
  "description": "The organization's description"
}

Response
{
  "id": 1,
  "name": "Organization's name",
  "description": "The organization's description"
}
----

*Read all organizations*

----
GET /organizations

Response
[
  {
    "id": 1,
    "name": "Organization's name",
    "description": "The organization's description"
  }
]
----

For operations that return multiple entities, a number of default parameters are available that support typical use
cases like paging or sorting. They can be added to the request URL as query parameters as shown below:

 GET /organizations?limit=25&offset=100&sort=-name

The query parameters have the following meaning:

[cols="1,4",options="header"]
|===
|Parameter |Description

|limit
|Restricts the number of results to be retrieved. For paging, this parameter defines the page size.

|Offset
|Defines the offset of the first result to be retrieved.

|sort
|A comma-separated list of fields by which the result should be sorted. The field names are logic property names
which do not necessarily correspond to the database column names. (In many cases they do, but when defining an
entity, the developer can specify a deviating property name. Also, property names are case-sensitive.) They can be
prefixed with "-" for descending order or "+" for ascending order (which is the default). Note that only a subset of
the properties offered by an entity can be referenced as sort field; these properties must have been marked
explicitly in the table definition. This restriction was introduced to prevent poor performance of database queries,
since for efficient sorting typically an index needs to be defined on the affected column.
|===


*Read single organization*

----
GET /organizations/1

Response
{
  "id": 1,
  "name": "Organization's name",
  "description": "The organization's description"
}
----

*Update organizations*

Updating entities should be done via `PATCH` requests, which will only update the given values, while deleting entities should be explicitly stated via a `null` value.

----
PATCH /organizations/1

Request
{
  "name": "New organization name",
  "description": null
}

Response
{
  "id": 1,
  "name": "New organization name"
}
----

*Delete organizations*

----
DELETE /organization/1
----

== Products

*Create products*

As products are always created within the context of an organization, this creation endpoint will be placed under
`/organizations`.

----
POST /organizations/1/products

Request
{
  "name": "Product name",
  "description": "Product description"
}

Response
{
  "id": 22
  "name": "Product name",
  "description": "Product description"
}
----

*Read all products of an organization*

----
GET /organizations/1/products

Response
[
  {
    "id": 22
    "name": "Product name",
    "description": "Product description"
  }
]
----

*Read a single Product*

----
GET /products/22

Response
{
  "id": 22
  "name": "Product name",
  "description": "Product description"
}
----
