@startuml
actor "User" as user
participant "API" as api
participant "Orchestrator" as orchestrator
participant "Parameter check worker" as checkWorker
participant "Config file manager" as configManager
collections "Parameter check script" as script

user -> api: trigger run
activate api
api -> user: accepted
api -> orchestrator: forward
deactivate api
orchestrator -> checkWorker: runId
checkWorker -> checkWorker: load parameters
checkWorker -> configManager: getFile
configManager -> checkWorker: parameter config script
checkWorker -> script: run on parameters
script -> checkWorker: (mapped parameters, issues)
checkWorker -> checkWorker: save mapped parameters
checkWorker -> orchestrator: check result
orchestrator -> orchestrator: start next worker

@enduml
