@startuml
rectangle input [
Input
{{json
{
  "applicationCategory": "web",
  "useFossId": true,
  "fossIdInstance": "QM",
  "fossIdProject": "my-fossid-project",
  "fossIdDeltaScans": 7
}
}}
]

collections "Validation script" as script

rectangle output [
Output
{{json
{
  "scannerJobConfiguration": {
    "scannerOptions": {
      "FossID": {
        "url": "https://fossid-qm.example.org",
        "username": "secret:fossIdUser_QM",
        "password": "secret:fossIdPass_QM",
        "project": "my-foss-id-project",
        "maxDeltaScans": 7
      }
    }
  },
  "evaluatorJobConfiguration": {
    "ruleSet": "evaluator/rules/web.kts",
    "classifications": "evaluator/classifications/web.json"
  }
}
}}
]

input --> script: validate & transform
script --> output

@enduml
