name: Validate Gradle Wrapper

on:
  merge_group:
    types: [ checks_requested ]
  pull_request:
    branches:
    - main
  push:
    branches:
    - main

jobs:
  wrapper-validation:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Validate Wrapper
      uses: gradle/actions/wrapper-validation@v3
