name: Publish Website

on:
  push:
    branches:
    - main

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    if: github.repository == 'eclipse-apoapsis/ort-server'
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout Repository
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@3f131e8634966bd73d06cc69884922b02e6faf92 # v6.2.0

    - name: Generate OpenAPI spec
      run: ./gradlew --stacktrace :core:generateOpenApiSpec

    - name: Install Node
      uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
      with:
        node-version: 24
        cache-dependency-path: website/pnpm-lock.yaml

    - name: Enable Corepack
      run: corepack enable

    - name: Install dependencies
      working-directory: website
      run: pnpm install --frozen-lockfile

    - name: Test build
      working-directory: website
      run: pnpm build

    - name: Setup Pages
      uses: actions/configure-pages@45bfe0192ca1faeb007ade9deae92b16b8254a0d # v6.0.0

    - name: Upload artifact
      uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9 # v5.0.0
      with:
        path: website/build

  deploy:
    if: github.repository == 'eclipse-apoapsis/ort-server'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-24.04
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128 # v5.0.0
