= HashiCorp Vault Secret Provider Implementation

This module provides an implementation of the link:../README.adoc[Secrets Abstraction Layer] based on
https://www.vaultproject.io/[HashiCorp Vault].

== Synopsis
The link:src/main/kotlin/VaultSecretsProvider.kt[VaultSecretsProvider] class implemented here communicates with the
REST API of HashiCorp Vault to access secrets managed by this service.

The interaction with the Vault service is done via the
https://developer.hashicorp.com/vault/api-docs/secret/kv/kv-v2[KV Secrets Engine Version 2], which means that
versioning of secrets is available.

For authentication, the https://developer.hashicorp.com/vault/api-docs/auth/approle[AppRole] authentication method is
used. The ORT Server application must be assigned a role with a policy that grants the required access rights to the
secrets to be managed. The ID of this role and a corresponding _secret Id_ must be provided as credentials. Based on
this, the provider implementation can obtain an access token from the Vault service. Refer to the
https://developer.hashicorp.com/vault/tutorials/auth-methods/approle[AppRole Pull Authentication Tutorial] for further
details.

The Secrets Abstraction Layer operates on plain keys for secrets and does not support any hierarchical relations
between keys. To map those keys to specific paths in Vault, the provider implementation can be configured with a
_root path_ that is simply prefixed to the passed in paths for accessing secrets. Via this mechanism, it is possible
for instance that different provider instances (e.g. for production or test) access different parts of the Vault
storage.

Another difference between the abstraction layer and Vault is that secrets in Vault can have an arbitrary number of
key value pairs stored under the secret's path, while the abstraction layer assigns only a single value to the secret.
This implementation handles this by using a default key internally. So, when writing a secret, `VaultSecretsProvider`
actually writes a secret at the path specified that has a specific key with the given value. Analogously, this default
key is read when querying the value of a secret. This speciality has to be taken into account when creating or updating
secrets directly in Vault that should be accessible by the Vault abstraction implementation.

== Configuration
As defined by the Secrets SPI module, the configuration takes place in a section named `secretsProvider`. Here a
number of Vault-specific properties can be set as shown by the fragment below. The service URI and the credentials
are mandatory.

.Configuration of the Vault secrets provider
[source]
----
secretsProvider {
  name = "vault"
  vaultUri = "https://vault-service-uri.io"
  vaultRoleId = "<ID of the role assigned to the application>"
  vaultSecretId = "<secret ID>"
  rootPath = "path/to/my/secrets"
}
----
